#include <Adafruit_AHTX0.h>
#include <Adafruit_BME280.h>
#include <Adafruit_SSD1306.h>
#include <Adafruit_VL53L0X.h>
#include <BH1750.h>
#include <DFRobot_MAX17043.h>
#include <LCD_I2C.h>
#include <WiFi.h>
#include <OneWire.h>
#include <DallasTemperature.h>
#include <Wire.h>

#include <secrets.h>
#include <sensordata.h>
#include <time.h>       // NTP-set wall-clock for sleep-duration snapping to round minutes
#include "version.h"    // FIRMWARE_VERSION — generated by gen_version.sh from git HEAD before flash

// secrets are located in secrets.h
// #define WIFI_SSID "xxx"
// #define WIFI_PASSWORD "xxx"

// ---------- GPIO pin assignments ----------
#define BUTTON_PIN        15   // green push button (EXT0 wake source, preserves RTC memory)
#define GREEN_LED_PIN     2    // status "OK" LED (boot done, sleep, per-channel POST success)
#define RED_LED_PIN       4    // status "ERROR" LED (init/WiFi/POST failures)
#define BLUE_LED_PIN      16   // solid ON while posting to ThingSpeak
#define BUZZER_PIN        32   // piezo — short beep at boot and sleep
#define SENSOR_POWER_PIN  13   // HIGH powers the sensor rail; goes LOW in enterDeepSleep()
#define POST_SWITCH_PIN   27   // black rocker switch: LOW = post to ThingSpeak, HIGH = skip
#define SOIL_1_PIN        34   // analog: soil moisture sensor 1
#define SOIL_2_PIN        39   // analog: soil moisture sensor 2
#define SOIL_3_PIN        36   // analog: soil moisture sensor 3
#define ONE_WIRE_PIN      23   // OneWire bus for the 3 DS18B20 (Dallas) temperature sensors

// ---------- LED flash-count codes (see QUICK_REFERENCE.md) ----------
#define FLASH_WIFI_CONNECT_FAILURE 4   // red x 4 (before blue LED = WiFi failed to associate)
#define FLASH_DISPLAY_INIT_FAILURE 3   // red x 3 (before blue LED = SSD1306 display init failed)
#define FLASH_DEFAULT_MS 180           // default on/off duration for flashLED() when caller omits explicit values

// ---------- Environmental classification thresholds (drive the status field) ----------
#define PRESSURE_LOW  999    // hPa; below → P-LOW
#define PRESSURE_HIGH 1010   // hPa; above → P-HIGH; between → P-OK
#define TEMP_COLD     5      // aggregate temp <= this → T-COLD (matches heat-frost.html frost=5 default)
#define TEMP_HOT      35     // aggregate temp >= this → T-HOT  (matches heat-frost.html heat=35 default)
#define NIGHT_LEVEL   5      // lux < this → NIGHT
#define DUSK_LEVEL    200    // lux between NIGHT and this → DUSK. Kept conservative: higher values would classify overcast Norwegian winter days as DUSK for hours, tripling wake frequency for no signal (light isn't actually transitioning, just dim).
#define SHADE_LEVEL   25000  // lux between DUSK and this → SHADE; above → SUN (calibrated Aug 2026 from observed sunny-vs-overcast lux data)
#define WINDOW_CLOSE  82     // distance sensor (mm) < this → W-CLOSE, else W-OPEN
#define BATTERY_LOW   35     // battery % < this → B-LOW

// ---------- WiFi behaviour ----------
#define WIFI_MAX_RETRIES              10   // fresh-scan retries after initial cache attempt fails
#define WIFI_FAILS_BEFORE_FRESH_SCAN  3    // if wifiFailStreak exceeds this, skip cached BSSID and force fresh scan
#define WIFI_INITIAL_TIMEOUT_MS       3000 // how long to wait for the initial cached-BSSID connect before retrying
#define WIFI_POLL_INTERVAL_MS         50   // how often WiFi.status() is polled while waiting for association
#define WIFI_RETRY_DELAY_MS           1000 // pause between each fresh-scan retry after the initial attempt fails

// ---------- Static WiFi config (4 comma-separated octets, consumed by IPAddress()) ----------
#define WIFI_STATIC_IP  192, 168, 1, 15    // ESP32's own IP on the LAN — outside DHCP pool
#define WIFI_GATEWAY    192, 168, 1, 1     // primary router (SOV_MF)
#define WIFI_SUBNET     255, 255, 255, 0   // /24
#define WIFI_DNS        192, 168, 1, 1     // reuse the gateway for DNS

// ---------- ThingSpeak posting ----------
#define THINGSPEAK_INTER_POST_MS 10   // brief settle after client.stop() before next channel POST
#define POST_FLASH_ON_MS 300          // LED-on duration for the 3 post-POST channel-result flashes (off stays at flashLED default 180 ms)
#define MAX_POST_RETRY 2              // extra attempts per channel on transient network errors (0/-301/-302/-303/-304). Total attempts = 1 + MAX_POST_RETRY.
#define POST_RETRY_DELAY_MS 750       // pause between retry attempts on the same channel (after client.stop()). Long enough for TCP to settle, short enough not to shift the next boundary.

// ---------- Serial ----------
#define SERIAL_BAUD 115200   // serial monitor baud (dev-time only; not visible in production)

// ---------- Sensor plausibility bounds ----------
#define DALLAS_MIN_C          -20.0   // below this = bogus (DS18B20 bit-corrupt or disconnect: -55, -127, 85, …)
#define DALLAS_MAX_C           60.0   // above this = bogus
#define DALLAS_RETRIES         2      // extra requestTemperatures() attempts on an implausible read
#define TOF_MAX_MM             8000   // VL53L0X out-of-range cutoff (readings ≥ this are dropped)
#define TOF_INTERVAL_MS        12     // delay between successive TOF distance samples
#define TERMO2_INCLUDE_MIN_C   0.0    // range for including DS18B20 middle sensor (termo2) in temp aggregate;
#define TERMO2_INCLUDE_MAX_C   60.0   // outside → aggregate falls back to BME + AHT only

// ---------- Measurement loop ----------
#define NUM_READINGS           2    // how many times each I²C sensor is sampled per wake (averaged)
#define NUM_DISTANCE_READINGS  10   // how many TOF distance samples are taken (best-effort averaged, drops invalid)
#define SLEEP_BETWEEN_READINGS 12   // ms between successive samples inside NUM_READINGS loop
#define HEIGHT_ABOVE_SEA_LEVEL 31   // meters — added into BME pressure reading for sea-level normalisation

// ---------- Display behaviour ----------
#define DISPLAY_TIME 8000   // ms to keep the OLED/LCD lit for reading (button/fresh wake only; SD- token records this)

// ---------- Deep-sleep intervals (minutes), selected by ambient light level ----------
// Intervals chosen so that mult=1 (in-season) AND mult=3 (off-season) both land on tidy minute boundaries:
//   dusk : in-season 5 min (:00,:05,:10…) / off-season 15 min (:00,:15,:30,:45)
//   day  : in-season 10 min (:00,:10,:20…) / off-season 30 min (:00,:30)
//   night: in-season 20 min (:00,:20,:40) / off-season 60 min (:00 hourly)
#define SLEEP_INTERVAL_DUSK_MIN   5   // lux between NIGHT and DUSK
#define SLEEP_INTERVAL_DAY_MIN    10  // daytime — most wakes
#define SLEEP_INTERVAL_NIGHT_MIN  20  // below NIGHT_LEVEL — chosen so ×3 = 60 min off-season (clean hourly)

// ---------- Growing season & off-season power saving ----------
// In-season = greenhouse actively used (10 Apr – 10 Sep). Off-season sleeps this many times longer to save battery
// (fewer daylight hours, less sun on the panel, no plants to monitor). Multiplier applies to both snap intervals
// AND the fallback SLEEP_DURATION_* — chosen alongside SLEEP_DURATION_NIGHT so all boundaries are clean.
#define SEASON_START_MONTH   4    // April (1-based)
#define SEASON_START_DAY     10
#define SEASON_END_MONTH     9    // September (1-based)
#define SEASON_END_DAY       10
#define SEASON_MULT_OFFSEASON 3   // 1 = same as in-season; 3 triples sleep during off-season

#define SNAP_BOUNDARY_BUFFER_SEC 30  // added to every snapped sleep. ESP32 uses its internal 150 kHz RC oscillator for deep-sleep timing (±5 % accuracy), so a 10-min sleep can drift up to ±30 s. Buffer covers the "wake early" side so posts still land inside the intended minute even at worst-case drift.

int dispLine = 0;
bool SHOULD_POST = false;
bool DISPLAY_ON = false;
bool TOF_OK = false;
uint8_t g_resetReason = 0;   // esp_reset_reason() at setup start — 8 = ESP_RST_DEEPSLEEP (normal), anything else = cold-path reset that wiped RTC
uint8_t g_wakeupCause = 0;   // esp_sleep_get_wakeup_cause() at setup start — 4 = TIMER, 2 = EXT0, 0 = UNDEFINED (fresh boot)

// All RTC_DATA_ATTR vars live here: Arduino concatenates the main sketch first, so any variable
// referenced from setup() must be declared here to be in scope. Grouping the rest here too so all
// wake-crossing state is in one place.
RTC_DATA_ATTR uint8_t cachedBSSID[6] = {0};
RTC_DATA_ATTR int32_t cachedChannel = 0;
RTC_DATA_ATTR uint16_t wifiFailStreak = 0;    // consecutive wakes where WiFi never associated; wiped by cold reset
RTC_DATA_ATTR uint16_t postFailStreak = 0;    // consecutive wakes where WiFi was OK but ALL 3 POSTs failed; wiped by cold reset
RTC_DATA_ATTR int lastPostResults[3] = {0, 0, 0};   // HTTP codes from previous wake's 3 channel POSTs
RTC_DATA_ATTR uint8_t postRetryCounts[3] = {0, 0, 0};   // per-channel EXTRA attempts used in previous wake (0 = no retry, up to MAX_POST_RETRY)
RTC_DATA_ATTR uint16_t lastPostTimeMs = 0;    // ms spent inside postThingSpeak() during the previous wake (retries + inter-post delays)
RTC_DATA_ATTR uint16_t lastTotalTimeMs = 0;   // ms for the entire previous wake (setup → just before enterDeepSleep); measure + post + display + tail
RTC_DATA_ATTR uint16_t lastMeasureTimeMs = 0; // previous wake's measure time (same as that wake's own TU); emitted as LTU- to keep decomposition on one status row

Adafruit_SSD1306 display(128, 64, &Wire, -1);
LCD_I2C lcd(0x27, 16, 2);
Adafruit_VL53L0X tof = Adafruit_VL53L0X();
Adafruit_BME280 bme;
BH1750 lightMeter(0x5C);
BH1750 lightMeter_int(0x23);
Adafruit_AHTX0 aht;
DFRobot_MAX17043 batteryMonitor;
DeviceAddress termo1 = { 0x28, 0xAD, 0x1B, 0x46, 0xD4, 0x4D, 0x17, 0x66 };  // closest
DeviceAddress termo2 = { 0x28, 0x0E, 0xE5, 0x6A, 0x00, 0x00, 0x00, 0x8E };  // middle
DeviceAddress termo3 = { 0x28, 0xBE, 0x62, 0x6B, 0x00, 0x00, 0x00, 0x9C };  // farthest
OneWire oneWire(ONE_WIRE_PIN);
DallasTemperature sensors(&oneWire);
WiFiClient client;



void dispPrint(String msg) {
  if (DISPLAY_ON) {
    display.setCursor(0, dispLine);
    display.print("                     ");
    display.setCursor(0, dispLine);
    display.print(msg);
    display.display();
    if (dispLine < 50) {
      dispLine += 9;
    } else {
      dispLine = 0;
    }
  }
}

void beep(int del = 100) {
  digitalWrite(BUZZER_PIN, HIGH);
  delay(del);
  digitalWrite(BUZZER_PIN, LOW);
  delay(del);
}

void flashLED(int pin, int times, int onMs = FLASH_DEFAULT_MS, int offMs = FLASH_DEFAULT_MS) {
  for (int i = 0; i < times; i++) {
    digitalWrite(pin, HIGH);
    delay(onMs);
    digitalWrite(pin, LOW);
    delay(offMs);
  }
}

void setup() {
  long start = millis();
  setupPins();
  beep(50);
  flashLED(GREEN_LED_PIN, 2);
  Serial.begin(SERIAL_BAUD);

  Serial.println("Setup...");
  g_resetReason = (uint8_t)esp_reset_reason();
  g_wakeupCause = (uint8_t)esp_sleep_get_wakeup_cause();
  Serial.printf("  Reset reason %u, wakeup cause %u\n", g_resetReason, g_wakeupCause);
  esp_sleep_wakeup_cause_t wakeup_reason = (esp_sleep_wakeup_cause_t)g_wakeupCause;
  if (wakeup_reason == ESP_SLEEP_WAKEUP_EXT0) {
    SHOULD_POST = digitalRead(POST_SWITCH_PIN) == LOW;
    DISPLAY_ON = true;
    Serial.println("  Woke up from deep sleep by button press");
  } else if (wakeup_reason == ESP_SLEEP_WAKEUP_TIMER) {
    SHOULD_POST = digitalRead(POST_SWITCH_PIN) == LOW;
    Serial.println("  Woke up from deep sleep by timer");
  } else {
    // Fresh boot (cold reset: POWERON/EXT/BROWNOUT/PANIC/…) — RTC state was wiped, WF cache is empty,
    // wake cause is UNDEFINED. Still POST so the WR token surfaces the reset reason on ThingSpeak.
    SHOULD_POST = digitalRead(POST_SWITCH_PIN) == LOW;
    // Only light displays on human-triggered cold boots (POWERON=battery reconnect, EXT=EN-button
    // press). PANIC/WDT/BROWNOUT/SW = code died with no human around — keep dark to preserve battery
    // (11-h panic-restart loop 2026-08-08→09 burned ~130 mAh on 8 s display-pauses per wake).
    // Whitelist so any new ESP-IDF reset cause defaults to dark.
    DISPLAY_ON = (g_resetReason == ESP_RST_POWERON || g_resetReason == ESP_RST_EXT);
    Serial.println("  Starting fresh");
  }

  initDisplays();
  connectToWiFi();  // not really neded when pressing button, but nic to see status...

  if (SHOULD_POST) {
    Serial.println("  Will POST");
    dispPrint("Will POST");
  } else {
    Serial.println("  Will NOT post");
    dispPrint("Will NOT POST");
  }

  initSensors();

  Serial.println("Setup: done");

  delay(200);

  Serial.println("Measuring...");
  dispPrint("Measuring...");
  SensorData data = measure(start);
  Serial.println("Measuring: done");


  dispPrint("Done!");

  Serial.println("Displaying data...");
  displayData(data);
  Serial.println("Displaying data: done");
  if (SHOULD_POST) {
    postThingSpeak(data);
  }
  else{
    Serial.println("NOT Posting data to ThingSpeak...");
  }
  if (DISPLAY_ON) {
    Serial.printf("Sleeping %d ms for the display to be read...\n", DISPLAY_TIME);
    delay(DISPLAY_TIME);
  }

  flashLED(GREEN_LED_PIN, 2);
  beep(40);
  beep(40);

  int sleepDuration = getSleepDuration(data.lux);
  long totalElapsed = millis() - start;
  lastTotalTimeMs = totalElapsed > UINT16_MAX ? UINT16_MAX : (uint16_t)totalElapsed;
  lastMeasureTimeMs = data.timeUsed > UINT16_MAX ? UINT16_MAX : (uint16_t)data.timeUsed;
  Serial.printf("Total wake time %ld ms (measure %ld, post %u). Sleeping %d s.\n", totalElapsed, data.timeUsed, lastPostTimeMs, sleepDuration);
  enterDeepSleep(sleepDuration);
}

void loop() {  // do nothing
}
