#!/usr/bin/env bash
# Regenerates version.h from the current git HEAD.
# Run before Arduino IDE compile/flash so the binary carries the correct commit hash.
# Uncommitted changes in this sketch folder append a "+" (dirty) marker.

cd "$(dirname "$0")" || { echo "gen_version.sh: cannot cd to sketch folder" >&2; exit 1; }

REPO_ROOT=$(git rev-parse --show-toplevel) || {
    echo "gen_version.sh: not inside a git repository" >&2
    exit 1
}

HASH=$(git -C "$REPO_ROOT" rev-parse --short HEAD) || {
    echo "gen_version.sh: git rev-parse failed" >&2
    exit 1
}

DIRTY=""
git -C "$REPO_ROOT" diff --quiet HEAD -- "$(pwd)" || DIRTY="+"

cat > version.h <<EOF
// Auto-generated by gen_version.sh — DO NOT EDIT MANUALLY.
// Run \`./gen_version.sh\` in this directory before compiling to refresh with the current git commit.
// If left unrefreshed, FIRMWARE_VERSION reads as "unknown" and status field shows \`V-unknown\`.
#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "${HASH}${DIRTY}"
#endif
EOF

echo "version.h updated: FIRMWARE_VERSION = ${HASH}${DIRTY}"
